export const ADD_SERVICE = "ADD_SERVICE";
export const ADD_BOOKING_DATE = "ADD_BOOKING_DATE";
export const ADD_BOOKING_TIME = "ADD_BOOKING_TIME";

export const UPDATE_BOOKING_DATE = "UPDATE_BOOKING_DATE";
export const UPDATE_BOOKING_TIME = "UPDATE_BOOKING_TIME";
